### ISSUE TITLE
0.2.4 fails to build with nan@1.5.2

### ISSUE THREAD

**Issue by byronclark** [ddopson/node-segfault-handler#20]
Seeing this build error with nan@1.5.2:

```
% npm install segfault-handler
\
> segfault-handler@0.2.4 install /home/bclark/tmp/node_modules/segfault-handler
> node-gyp rebuild


module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bclark/tmp/node_modules/segfault-handler
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! segfault-handler@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@0.2.4 install script.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "segfault-handler"
npm ERR! cwd /home/bclark/tmp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by byronclark** [comment]
Building with nan@1.5.1 works:

```
% npm install nan@1.5.1 segfault-handler
\
> segfault-handler@0.2.4 install /home/bclark/tmp/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory `/home/bclark/tmp/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
../src/segfault-handler.cpp: In function ‘void segfault_handler(int, siginfo_t*, void*)’:
../src/segfault-handler.cpp:41:33: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
../src/segfault-handler.cpp:42:29: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node: Finished
  COPY Release/segfault-handler.node
make: Leaving directory `/home/bclark/tmp/node_modules/segfault-handler/build'
nan@1.5.1 node_modules/nan

segfault-handler@0.2.4 node_modules/segfault-handler
└── bindings@1.2.1
```

**Comment by No9** [comment]
I am closing this as 2.0 landed here https://github.com/ddopson/node-segfault-handler/pull/26
If there is something else crops up please open another pull request
